WOLFSSL_PATH := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))/src/wolfSSL

SRC += $(wildcard $(PWD)/platforms/default/wolf/crypt/*.c)
SRC += $(shell find $(PWD)/src/wolfSSL -name "*.c")

INCLUDES += \
    -I$(WOLFSSL_PATH) \
    -I$(WOLFSSL_PATH)/wolfssl
